openapi: 3.0.0
info:
  title: Cat Facts API
  version: '1.0'
paths:
  /breeds:
    get:
      tags:
        - Breeds
      summary: Get a list of breeds
      description: Returns a a list of breeds
      operationId: getBreeds
      parameters:
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Breeds'
  /fact:
    get:
      tags:
        - Facts
      summary: Get Random Fact
      description: Returns a random fact
      operationId: getRandomFact
      parameters:
        - name: max_length
          in: query
          description: maximum length of returned fact
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatFact'
        '404':
          description: Fact not found
  /facts:
    get:
      tags:
        - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
        - name: max_length
          in: query
          description: maximum length of returned fact
          required: false
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatFacts'
components:
  schemas:
    Link:
      title: Links
      description: Links
      properties:
        url:
          title: URL
          description: URL
          type: string
          format: string
        label:
          title: Label
          description: Label
          type: string
          format: string
        active:
          title: Active
          description: Active
          type: boolean
    Breed:
      title: Breed model
      description: Breed
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    Breeds:
      title: Breeds model
      description: List of Breeds
      properties:
        current_page:
          title: Current page
          description: Current page
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: '#/components/schemas/Breed'
        first_page_url:
          title: First page URL
          description: First page URL
          type: string
          format: string
        from:
          title: From
          description: From
          type: integer
          format: int32
        last_page:
          title: Last page
          description: Last page
          type: integer
          format: int32
        last_page_url:
          title: Last page URL
          description: Last page URL
          type: string
          format: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        next_page_url:
          title: Next page URL
          description: Next page URL
          type: string
          format: string
        path:
          title: Path
          description: Path
          type: string
          format: string
        per_page:
          title: Per page
          description: Per page
          type: integer
          format: int32
        prev_page_url:
          title: Prev page URL
          description: Prev page URL
          type: string
          format: string
        to:
          title: To
          description: To
          type: integer
          format: int32
        total:
          title: Total
          description: Total
          type: integer
          format: int32
    CatFact:
      title: CatFact model
      description: CatFact
      properties:
        fact:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
      type: object
    CatFacts:
      title: Breeds model
      description: List of Breeds
      properties:
        current_page:
          title: Current page
          description: Current page
          type: integer
          format: int32
        data:
          type: array
          items:
            $ref: '#/components/schemas/CatFact'
        first_page_url:
          title: First page URL
          description: First page URL
          type: string
          format: string
        from:
          title: From
          description: From
          type: integer
          format: int32
        last_page:
          title: Last page
          description: Last page
          type: integer
          format: int32
        last_page_url:
          title: Last page URL
          description: Last page URL
          type: string
          format: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        next_page_url:
          title: Next page URL
          description: Next page URL
          type: string
          format: string
        path:
          title: Path
          description: Path
          type: string
          format: string
        per_page:
          title: Per page
          description: Per page
          type: integer
          format: int32
        prev_page_url:
          title: Prev page URL
          description: Prev page URL
          type: string
          format: string
        to:
          title: To
          description: To
          type: integer
          format: int32
        total:
          title: Total
          description: Total
          type: integer
          format: int32